extends:
  - '@commitlint/config-conventional'

# https://github.com/conventional-changelog/conventional-changelog/issues/234#issuecomment-766839160
# https://github.com/ccnnde/commitlint-config-git-commit-emoji/blob/master/index.js#L4
parserPreset:
  parserOpts:
    headerPattern: ^((?<emoji_left>(?::\w*:|\ud83c[\udde0-\uddff]|\ud83c[\udf00-\udfff]|\ud83d[\ude00-\ude4f]|\ud83d[\ude80-\udeff]|\ud83d[\udf00-\udf7f]|\ud83d[\udf80-\udfff]|\ud83e[\udc00-\udcff]|\ud83e[\udd00-\uddff]|\ud83e[\ude00-\ude6f]|\ud83e[\ude70-\udeff]|[\u2600-\u2B55]))\s)?(?<type>\w+)(?:\((?<scope>[^)]*)\))?!?:\s((?<emoji_center>(?::\w*:|\ud83c[\udde0-\uddff]|\ud83c[\udf00-\udfff]|\ud83d[\ude00-\ude4f]|\ud83d[\ude80-\udeff]|\ud83d[\udf00-\udf7f]|\ud83d[\udf80-\udfff]|\ud83e[\udc00-\udcff]|\ud83e[\udd00-\uddff]|\ud83e[\ude00-\ude6f]|\ud83e[\ude70-\udeff]|[\u2600-\u2B55]))\s)?(?<subject>(?:(?!#).)*(?:(?!\s).))(?:\s(?<ticket>#(?<ticket_number1>\w+)|\(#(?<ticket_number2>\w+)\)))?(?:\s(?<emoji_right>(?::\w*:|\ud83c[\udde0-\uddff]|\ud83c[\udf00-\udfff]|\ud83d[\ude00-\ude4f]|\ud83d[\ude80-\udeff]|\ud83d[\udf00-\udf7f]|\ud83d[\udf80-\udfff]|\ud83e[\udc00-\udcff]|\ud83e[\udd00-\uddff]|\ud83e[\ude00-\ude6f]|\ud83e[\ude70-\udeff]|[\u2600-\u2B55])))?$
    headerCorrespondence: ['emoji_left_', 'emoji_left', 'type', 'scope', 'emoji_center_', 'emoji_center', 'subject', 'ticket', 'ticket_number1', 'ticket_number2', 'emoji_right']

rules:
  type-enum:
    - 2
    - always
    -
      - feat
      - perf
      - fix
      - refactor
      - docs
      - build
      - types
      - chore
      - examples
      - test
      - style
      - ci
      - init
prompt:
  messages:
    type: '选择你要提交的类型 :'
    scope: '选择一个提交范围 (可选) :'
    customScope: '请输入自定义的提交范围 :'
    subject: "填写简短精炼的变更描述 :\n"
    body: "填写更加详细的变更描述 (可选) 。使用 \"|\" 换行 :\n"
    breaking: "列举非兼容性重大的变更 (可选) 。使用 \"|\" 换行 :\n"
    footerPrefixesSelect: '设置关联issue前缀 (可选) :'
    customFooterPrefix: '输入自定义issue前缀 :'
    footer: "列举关联issue (可选) 例如: #1 :\n"
    confirmCommit: 是否提交或修改commit ?
  types:
    - value: feat
      name: '🚀 Features: 新功能'
      emoji: 🚀
    - value: perf
      name: '🔥 Performance: 性能优化'
      emoji: 🔥
    - value: fix
      name: '🩹 Fixes: 缺陷修复'
      emoji: 🩹
    - value: refactor
      name: '💅 Refactors: 代码重构'
      emoji: 💅
    - value: docs
      name: '📖 Documentation: 文档'
      emoji: 📖
    - value: build
      name: '📦 Build: 构建工具'
      emoji: 📦
    - value: types
      name: '🌊 Types: 类型定义'
      emoji: 🌊
    - value: chore
      name: '🏡 Chore: 简修处理'
      emoji: 🏡
    - value: examples
      name: '🏀 Examples: 例子展示'
      emoji: 🏀
    - value: test
      name: '✅ Tests: 测试用例'
      emoji: ✅
    - value: style
      name: '🎨 Styles: 代码风格'
      emoji: 🎨
    - value: ci
      name: '🤖 CI: 持续集成'
      emoji: 🤖
    - value: init
      name: '🎉 Init: 项目初始化'
      emoji: 🎉
  useEmoji: true
  emojiAlign: left
  scopes: []
  maxHeaderLength: 72
